build_debian10:
  image: debian:10-slim
  stage: build
  before_script:
    - apt-get update && apt-get -y install fp-compiler fp-units-gfx freeglut3
  script:
    - cd ./engine
    - fpc -S2 vespucci.dpr

build_centos8:
  image: centos:8
  stage: build
  before_script:
    - yum install -y epel-release && yum install -y fpc freeglut glibc-devel
  script:
    - cd ./engine
    - fpc -S2 vespucci.dpr
